----------------------------------------------------------------------------------------------------
-- Szinkronfeliratok
----------------------------------------------------------------------------------------------------
-- Készítette: ·f·i· csoport
-- Mr. Fusion (mrf_of_vsb@hotmail.com)
-- The Sweet Little 16-bit (tsl16b@freemail.hu)
----------------------------------------------------------------------------------------------------

-- caption type override table
-- snd_id	= {cc_type, showtime, sendericon, faction, name, distance_limit}
-- cc_type	= -1: incoming message, -2: memo, -3: sending message, -4: (none)

local snd_ids = {
["cc_effect-device-door_start"]					= {9, 1500, nil, nil, nil, 20},
["cc_effect-device-door_closing"]				= {9, 1500, nil, nil, nil, 20},
["cc_effect-device-door_stop"]					= {9, 1500, nil, nil, nil, 20},
["cc_effect-device-metal_small_open"]				= {9, 1500, nil, nil, nil, 15},
["cc_effect-device-power_switch"]				= {9, 1500},
["cc_effect-device-radio_call"]					= {9, 2500},
["cc_effect-device-wood_large_open"]				= {9, 1500, nil, nil, nil, 10},
["cc_effect-device-wood_large_close_start"]			= {9, 1500, nil, nil, nil, 10},
["cc_effect-ambient-blowout_begin"]				= {9, 2500},

["cc_effect-anomaly-steam_blowout"]				= {9, nil, nil, nil, nil, 25},
["cc_effect-weapons-n_desert_eagle_shot"]			= {9, 1000, nil, nil, nil, 30},	-- scene triggered at around 25m

["cc_effect-music-guitar_"]					= {9, 3500, nil, nil, nil, 15},
["cc_effect-music-harmonica_"]					= {9, 3500, nil, nil, nil, 15},
["cc_effect-laughter_"]						= {9, 2500, nil, nil, nil, 15},

["cc_effect-ambient-zaton-zat_b38_bloodsucker_roar"]		= {6, 3500},
["cc_effect-ambient-zaton-zat_b38_electro_box_door"]		= {9, 1500},
["cc_effect-ambient-zaton-zat_b38_electro_box_switch"]		= {9, 1500},
["cc_effect-ambient-zaton-zat_b38_elevator_door"]		= {9},
["cc_effect-ambient-zaton-zat_b38_cop_elevator_landing"]	= {9},
["cc_effect-ambient-zaton-zat_b38_lock_sound"]			= {9},
["cc_effect-ambient-zaton-zat_b57_bloodsucker_roar"]		= {6, 3500},
["cc_effect-ambient-jupiter-jup_b16_oasis_noise"]		= {9, 1250},
["cc_effect-ambient-jupiter-jup_b41_steam"]			= {9},
["cc_effect-ambient-jupiter-jup_b46_spatial_bubble_idle"]	= {9},
["cc_effect-ambient-jupiter-jup_b46_spatial_bubble_rupture"]	= {9},
["cc_effect-ambient-jupiter-jup_b219_generator_start"]		= {9, 2500},
["cc_effect-ambient-jupiter-jup_b219_underpass_opening"]	= {9, 4000},
["cc_effect-ambient-underpass-pas_b400_elevator_off"]		= {9},
["cc_effect-ambient-pripyat-pri_a25_blow_up_door_peep"]		= {9, 4000},
["cc_effect-ambient-pripyat-pri_a25_freezer_knock"]		= {9, 1800, nil, nil, nil, 14},

-- ***** Zaton *****

--- Skadovsk announcements
["zat_a2_base_megaphone_1"]		= {8},
["zat_a2_base_megaphone_2"]		= {8},
["zat_a2_base_megaphone_3"]		= {8},
["zat_a2_base_alarm"]			= {-1, nil, "ui_inGame2_Boroda", "stalker", "zat_a2_stalker_barmen_name"},	-- actor override
["zat_a2_base_relax"]			= {-1, nil, "ui_inGame2_Boroda", "stalker", "zat_a2_stalker_barmen_name"},	-- actor override
["zat_a2_stalker_barmen_surge_phase_1"]	= {-1, nil, "ui_inGame2_Boroda", "stalker", "zat_a2_stalker_barmen_name"},	-- actor override
["zat_a2_stalker_barmen_surge_phase_2"]	= {-1, nil, "ui_inGame2_Boroda", "stalker", "zat_a2_stalker_barmen_name"},	-- actor override
["zat_a2_stalker_barmen_after_surge"]	= {-1, nil, "ui_inGame2_Boroda", "stalker", "zat_a2_stalker_barmen_name"},	-- actor override

--- Actor voice logs
["zat_b101_one_heli_info"]		= {-2},
["zat_b100_heli_2_maps"]		= {-2, 18000},
["zat_b101_both_heli_info"]		= {-2, 8000},
["zat_b28_heli_3_evacuation_points"]	= {-2, 20000},
["zat_a23_about_x8"]			= {-2, 12000},

--- Voice logs
["zat_b39_joker_pda_record"]	= {-2, nil, "ui_inGame2_neutral_2", "stalker", "st_joker_name"},
["zat_b44_stalker_barge_pda"]	= {-2, nil, "ui_inGame2_neutral_2_mask", "stalker", "zat_b44_stalker_barge_name"},
["zat_b20_noah_pda"]		= {-2, nil, "ui_inGame2_Noy", "stalker", "zat_b18_noah_name"},
["zat_b22_stalker_medic_diary"]	= {-2, nil, "ui_inGame2_Tremor", "stalker", "zat_b22_stalker_medic_name"},

--- Noah's stuff
["zat_b20_noah_jumped"]	= {-1, nil, "ui_inGame2_Noy", "stalker", "zat_b18_noah_name"},	-- actor override

--- Talking controller
["zat_b42_controller_warning_1"]	= {4, 3000},
["zat_b42_controller_warning_2"]	= {4, 3000},

--- New task messages (actor override)
["zat_b38_stalker_cop_find_lair_pda"]	= {-1, nil, "ui_inGame2_Gluhar", "stalker", "st_zat_b38_stalker_cop_name"},
["zat_b30_owl_about_trouble"]		= {-1, nil, "ui_inGame2_Sich", "stalker", "st_zat_b30_owl_stalker_trader_name"},

--- Order ready at Nimble (actor override)
["zat_b51_stalker_nimble_order"]	= {-1, nil, "ui_inGame2_neutral_1", "stalker", "st_zat_a2_stalker_nimble_name"},

-- ***** Jupiter *****

--- Janov announcements
["jup_a6_base_megaphone_1"]		= {8},
["jup_a6_base_megaphone_2"]		= {8},
["jup_a6_base_megaphone_3"]		= {8},
["jup_a6_base_alarm"]			= {-1, nil, "ui_inGame2_Kostoprav", "stalker", "jup_a6_stalker_medik"},	-- actor override
["jup_a6_base_relax"]			= {-1, nil, "ui_inGame2_Kostoprav", "stalker", "jup_a6_stalker_medik"},	-- actor override
["jup_a6_stalker_medik_phase_1"]	= {-1, nil, "ui_inGame2_Kostoprav", "stalker", "jup_a6_stalker_medik"},	-- actor override
["jup_a6_stalker_medik_phase_2"]	= {-1, nil, "ui_inGame2_Kostoprav", "stalker", "jup_a6_stalker_medik"},	-- actor override
["jup_a6_stalker_medik_after_surge"]	= {-1, nil, "ui_inGame2_Kostoprav", "stalker", "jup_a6_stalker_medik"},	-- actor override

--- Sci bunker announcements
["jup_b41_bunker_megaphone_1"]	= {8},
["jup_b41_bunker_megaphone_2"]	= {8},
["jup_b41_bunker_megaphone_3"]	= {8},
["jup_b41_base_alarm"]	= {-1, nil, "ui_inGame2_German", "ecolog", "jup_b6_scientist_nuclear_physicist"},	-- actor override
["jup_b41_base_relax"]	= {-1, nil, "ui_inGame2_German", "ecolog", "jup_b6_scientist_nuclear_physicist"},	-- actor override

--- Actor voice logs
["jup_a9_actor_conservation_info"]	= {-2},
["jup_a9_actor_power_info"]		= {-2},
["jup_a9_actor_way_info"]		= {-2},
["jup_b9_heli_1_blackbox"]		= {-2, 14500},

--- Voice logs
["jup_b46_duty_founder_pda_diary"]	= {-2, nil, "ui_inGame2_Dolg_4", "dolg", "jup_b46_duty_founder_name"},
["jup_b202_bandit_pda"]			= {-2, nil, "ui_inGame2_bandit_3", "bandit"},
["jup_b202_snag_pda"]			= {-2, nil, "ui_inGame2_neutral_1", "stalker", "zat_b33_stalker_snag"},

--- Blackbox recording (actor override)
["jup_b9_blackbox_records"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},

--- New task messages (actor override)
["jup_b212_trapper_found_chimera"]	= {-1, nil, "ui_inGame2_Zveroboy", "stalker", "jup_b220_trapper"},
["jup_b10_ufo_memory_repaired_nitro"]	= {-1, nil, "ui_inGame2_Azot", "stalker", "jup_b217_stalker_tech"},

--- North tunnel investigation (actor override)
["jup_b1_actor_dont_come"]		= {-1, nil, "ui_inGame2_neutral_2_mask", "stalker", "jup_b1_stalker_1"},	-- doesn't play(?)
["jup_b1_stalkers_monsters_beat_off"]	= {-1, nil, "ui_inGame2_neutral_2", "stalker", ""},

--- Entering "P-1" elevator scene
["jup_b219_tech_damn"]		= {-1, nil, "ui_inGame2_Azot", "stalker", "jup_b217_stalker_tech"},	-- actor override, doesn't (always?) play
--jup_b219_tech_success
["jup_b219_tech_ready"]		= {-1, nil, "ui_inGame2_Azot", "stalker", "jup_b217_stalker_tech"},	-- actor override
--jup_b219_duty_ready
--jup_b219_stalker_ready
--jup_b219_monolith_ready
--jup_b219_soldier_ready
["jup_b219_actor_ready"]	= {-3, nil, "ui_inGame2_Hero", "", "st_actor_name"},			-- actor_visual_stalker
["jup_b219_tech_opening"]	= {-1, nil, "ui_inGame2_Azot", "stalker", "jup_b217_stalker_tech"},	-- actor override
["jup_b219_actor_go"]		= {-3, nil, "ui_inGame2_Hero", "", "st_actor_name"},			-- actor_visual_stalker
["jup_b219_tech_to_duty"]	= {-1, nil, "ui_inGame2_Azot", "stalker", "jup_b217_stalker_tech"},	-- actor override
["jup_b219_duty_to_tech"]	= {-1, 3500, "ui_inGame2_Zulus", "", "jup_b15_zulus"},			-- actor override, doesn't play(?)

--- Spatial bubble messages (actor override)
["jup_b46_spatial_bubble_sos_1"]	= {-1, 3500, {"ui\\ui_noise_01", "ui\\ui_noise_00", "ui_inGame2_error_pic1"}, "", "!"},	-- "!": sender cannot be identified
["jup_b46_spatial_bubble_sos_2"]	= {-1, 7000, {"ui\\ui_noise_02", "ui\\ui_noise_04", "ui_inGame2_error_pic2"}, "", "!"},
["jup_b46_spatial_bubble_sos_3"]	= {-1, 5000, {"ui\\ui_noise_03", "ui_inGame_no_data", "ui_inGame2_error_pic3"}, "", "!"},

--- Anomaly measurement sequence (actor override)
["jup_b6_stalker_1_first_measurement_in_progress"]	= {-1, 3000, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_first_measurement_done"]		= {-1, 5000, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_second_measurement_in_progress"]	= {-1, 3500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_second_measurement_done"]		= {-1, 4000, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_third_measurement_in_progress"]	= {-1, 4500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_third_measurement_done"]		= {-1, 4500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_fourth_measurement_in_progress"]	= {-1, 4500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_fourth_measurement_done"]		= {-1, 3000, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_measurements_done"]			= {-1, 3500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_1"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_2"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_3"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_4"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_5"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},
["jup_b6_stalker_1_monsters_coming_6"]			= {-1, 2500, "ui_inGame2_neutral_2", "stalker", ""},

-- ***** Underpass *****

["pas_b400_sokolov_on_enemy_hit_1"]	= {9},
["pas_b400_sokolov_on_enemy_hit_2"]	= {9},
["pas_b400_sokolov_on_enemy_hit_3"]	= {9},
["pas_b400_vano_on_enemy_hit_1"]	= {9},
["pas_b400_vano_on_enemy_hit_2"]	= {9},
["pas_b400_vano_on_enemy_hit_3"]	= {9},
["pas_b400_wanderer_on_enemy_hit_1"]	= {9},
["pas_b400_wanderer_on_enemy_hit_2"]	= {9},
["pas_b400_wanderer_on_enemy_hit_3"]	= {9},
["pas_b400_zulus_on_enemy_hit_1"]	= {9},
["pas_b400_zulus_on_enemy_hit_2"]	= {9},
["pas_b400_zulus_on_enemy_hit_3"]	= {9},

-- ***** Pripyat *****

--- Army base announcements
["pri_a16_base_megaphone_1"]		= {8},
["pri_a16_base_megaphone_2"]		= {8},
["pri_a16_base_megaphone_3"]		= {8},
["pri_a16_base_alarm"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a16_base_relax"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a17_kovalsky_surge_phase_1"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a17_kovalsky_surge_phase_2"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a17_kovalsky_after_surge"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override

--- Pripyat reached scene
["pri_a15_army_hide_weapon"]			= {-4},
["pri_a15_sokolov_introduce"]			= {-4},
["pri_a15_actor_need_talk_with_commander"]	= {-4},
["pri_a15_sokolov_wonder"]			= {-4},
["pri_a15_army_who_a_you"]			= {-4},
["pri_a15_actor_introduce"]			= {-4},
["pri_a15_actor_introduce_squad"]		= {-4}, -- sound started but not played ?
["pri_a15_zulus_wonder"]			= {-4},
["pri_a15_sokolov_conjecture"]			= {-4},
["pri_a15_army_joke"]				= {-4},
["pri_a15_vano_speech_one"]			= {-4, nil, "ui_inGame2_Vano", "stalker", "jup_a10_stalker_vano"},
["pri_a15_army_go_with_me"]			= {-4},
["pri_a15_zulus_not_me"]			= {-4},
["pri_a15_zulus_no_business_with_army"]		= {-4},
["pri_a15_army_stop"]				= {-4},
["pri_a15_zulus_go"]				= {-4},
["pri_a15_actor_leave_him"]			= {-4},
["pri_a15_army_leave"]				= {-4},
["pri_a15_army_go"]				= {-4}, -- sound started but not played ?
["prI_a15_wanderer_about_actor"]		= {-4},

--- Zulu vs. snorks
["pri_b301_zulus_surrounded_1"]	= {-4, nil, nil, nil, nil, 35},
["pri_b301_zulus_surrounded_2"]	= {-4, nil, nil, nil, nil, 35},
["pri_b301_zulus_surrounded_3"]	= {-4, nil, nil, nil, nil, 35},
--pri_b301_zulus_hello_in_combat
--pri_b301_zulus_after_fight

--- Comms with recon unit scene
--pri_a20_communication_with_recon_squad
["pri_a20_recon_squad_attacked"]		= {-1, nil, "ui_inGame2_Soldier_2", "army", ""},	-- radio
["pri_a20_colonel_talk_in_radio"]		= {-4},
["pri_a20_colonel_ask_check_recon_squad"]	= {-4},

--- Recon unit found scene (actor override)
["pri_a20_actor_report_about_squad"]			= {-3},
["pri_a20_colonel_give_next_task_1"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a20_colonel_give_next_task_1_a21_sentry_task"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a20_actor_about_next_task"]			= {-3},
["pri_a20_actor_no_data"]				= {-3},
["pri_a20_colonel_send_reinforcement"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a20_colonel_send_reinforcement_a21_about_sentry"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a20_colonel_about_sentry"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a20_colonel_task_done"]				= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},

--- Bookstore assault sequence
--pri_a18_vano_hello
--pri_a18_sokolov_hello
--pri_a18_sokolov_on_place
["pri_a18_actor_report"]	= {-3},
["pri_a18_kovalskiy_guard"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a18_kovalskiy_squad"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a18_monolith_pray_1"]	= {3, 2300, nil, nil, nil, 10},
["pri_a18_monolith_pray_2"]	= {3, 2300, nil, nil, nil, 10},
["pri_a18_monolith_pray_3"]	= {3, 2800, nil, nil, nil, 10},

--- One shot (actor override)
["pri_b35_rendevous_started"]		= {-1, 3000, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_merc_leader_sighted"]		= {-1, 3500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_envoy_sighted"]		= {-1, 5000, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_rendevous_in_process"]	= {-1, 2500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_rendevous_done"]		= {-1, 2500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_primary_target_down"]		= {-1, 2500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_primary_target_lost_end"]	= {-1, 2500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_secondary_target_down"]	= {-1, 2500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_secondary_target_lost_end"]	= {-1, 3500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b35_both_done_end"]		= {-1, 5000, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},	-- doesn't (always?) play
["pri_b35_targets_lost_end"]		= {-1, 4500, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},

--- Lost sentry sequence/scene (actor override)
["pri_a21_colonel_give_sentry_task"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a21_colonel_base_about_sentry"]			= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a21_actor_to_base_find_controller"]		= {-3},
["pri_a21_actor_to_base_find_and_terminate_controller"]	= {-3},
["pri_a21_actor_to_base_terminate_controller"]		= {-3},
["pri_a21_base_to_actor_find_and_terminate_controller"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},
["pri_a21_base_to_actor_terminate_controller"]		= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},

--- Find RFI recon squad sequence/scene
["pri_a22_colonel_to_actor_need_talk"]		= {-1, 3500, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override
["pri_a22_colonel_about_situation"]		= {-4},
["pri_a22_colonel_about_rfi_and_lost_suad"]	= {-4},
["pri_a22_colonel_give_task"]			= {-4},

--- Found RFI recon squad scene
["pri_a22_actor_to_base_find_squad_member"]	= {-3},
["pri_a22_base_to_actor_has_rfi_coordinates"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override

--- Kindergarten doors blocked scene
["pri_a25_actor_all_doors_locked"]	= {-3},
["pri_a25_kovalski_take_explosive"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},	-- actor override

--- Medic in freezer scene
--pri_b305_kirilov_glad
--pri_b305_kirilov_what_happen
--pri_b305_medic_talk_later
--pri_b305_kirilov_ok
--pri_b305_kirilov_about_strelok_1
["pri_b305_actor_go"]			= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
--pri_b305_kirilov_about_garik / pri_b305_kirilov_about_garik_vano
["pri_b305_actor_understand"]		= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
-- cutscene ends, NPCs continue talking
--pri_b305_kirilov_where_you_been
--pri_b305_medic_in_freezer
--pri_b305_kirilov_what_freezer
--pri_b305_army_what_freezer
--pri_b305_medic_excuse
--pri_b305_kirilov_what_next
--pri_b305_medic_dont_know_what_say

--- Unknown signal detected scene
--pri_b305_kovalskiy_news
--pri_b305_kirilov_strange_signal
--pri_b305_kovalskiy_ask_coordinates
--pri_b305_kirilov_give_coordinates
--pri_b305_kovalskiy_think_of_attack
["pri_b305_actor_check_signal"]	= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker

--- Signal chase sequence/scene (-1: actor override, -3: actor_visual_stalker)
-- start in normal mode
["pri_b305_kirilov_give_new_coordinates"]	= {-1, nil, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b305_kirilov_signal_lost"]		= {-1, nil, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
-- switch to cutscene
["pri_b305_kirilov_signal_next_to_actor"]	= {-1, nil, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b305_actor_dont_see_anyone"]		= {-3, 3000, "ui_inGame2_Hero", "", "st_actor_name"},
["pri_b305_kirilov_source_is_near"]		= {-1, nil, "ui_inGame2_Soldier_2", "army", "st_pri_a22_army_signaller"},
["pri_b305_actor_it_is_underground"]		= {-3, nil, "ui_inGame2_Hero", "", "st_actor_name"},
["pri_b305_kovalskiy_attack_case_prepare"]	= {-1, nil, "ui_inGame2_Kovalskiy", "army", "pri_a17_military_colonel_kovalski_name"},

--- Strelok arrives scene
["pri_b305_strelok_give_up"]			= {-1, nil, "ui_inGame2_Strelok", "stalker", "pri_b305_strelok_name"},	-- actor override
["pri_b305_kovalskiy_who_are_you"]		= {-4},
["pri_b305_strelok_introduse"]			= {-4},
["pri_b305_actor_ask_about_burning_antenn"]	= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_b305_strelok_about_zone_destroying"]	= {-4},
["pri_b305_actor_emission_starts"]		= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_b305_kovalskiy_talk_in_safe_place"]	= {-4},
["pri_b305_actor_we_have_problems"]		= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
--pri_b305_kovalskiy_about_deal
--pri_b305_strelok_about_heli
--pri_b305_kovalskiy_about_anomaly_map
--pri_b305_strelok_about_anomaly_randomize
["pri_b305_actor_wondered"]			= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
--pri_b305_kovalskiy_wondered
--pri_b305_strelok_how_to_get_away
["pri_b305_actor_need_center_to_know"]		= {-4, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
--pri_b305_kovalskiy_let_center_know
-- switch to normal mode
--pri_b305_kovalskiy_order_kirilov
--pri_b305_kirilov_order_agree	-- doesn't always play

--- Comms with HQ/SSU command sequence/scene
-- start in normal mode
--pri_a28_colonel_after_surge
--pri_a28_signaller_after_surge_1
--pri_a28_signaller_after_surge_2
["pri_a28_center_to_colonel_1"]			= {-1, nil, "ui_inGame2_ssu_radio", "army", "st_hq_general_name"},
--pri_a28_colonel_to_center_1
["pri_a28_center_to_colonel_2"]			= {-1, nil, "ui_inGame2_ssu_radio", "army", "st_hq_general_name"},
--pri_a28_colonel_to_center_2
["pri_a28_center_to_colonel_3"]			= {-1, nil, "ui_inGame2_ssu_radio", "army", "st_hq_general_name"},
--pri_a28_colonel_to_center_3
-- switch to cutscene
["pri_a28_ssu_to_actor_1"]			= {-1, nil, "ui_inGame2_ssu_radio", "", "st_ssu_commander_name"},
["pri_a28_actor_to_ssu_1"]			= {-3, nil, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
-- switch to movie, adding movie captions to history by override
["pri_a28_ssu_to_actor_2"]			= {-1, 2500, "ui_inGame2_ssu_radio", "", "st_ssu_commander_name"},
["pri_a28_actor_to_ssu_2"]			= {-3, 2500, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_a28_ssu_to_actor_3"]			= {-1, 2500, "ui_inGame2_ssu_radio", "", "st_ssu_commander_name"},
["pri_a28_actor_to_ssu_with_heli_info"]		= {-3, 2500, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_a28_actor_to_ssu_without_heli_info"]	= {-3, 2500, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_a28_ssu_to_actor_5"]			= {-1, 2500, "ui_inGame2_ssu_radio", "", "st_ssu_commander_name"},
-- switch to normal mode
--pri_a28_colonel_instructions
--pri_a28_colonel_actor_talk

--- Evac related
--["pri_a28_colonel_cannot_wait"]			= {-4, 5000, "ui_inGame2_Kovalskiy", "", "pri_a17_military_colonel_kovalski_name"},
--pri_a28_colonel_wait_actor
--pri_a28_colonel_wait_actor_go
--pri_a28_colonel_wait_actor_long
["pri_a28_evac_com_helicopter_run_time"]	= {-1, 5000, "ui_inGame2_Soldier_2", "army", "pri_a28_evac_com_name"},	-- actor override
["pri_a28_evac_com_where_you"]			= {-1, 5000, "ui_inGame2_Soldier_2", "army", "pri_a28_evac_com_name"},	-- actor override
["pri_a28_evac_com_cant_wait"]			= {-1, 5000, "ui_inGame2_Soldier_2", "army", "pri_a28_evac_com_name"},	-- actor override
["pri_a28_evac_come_close"]			= {-1, 5000, "ui_inGame2_Soldier_2", "army", "pri_a28_evac_com_name"},	-- actor override
["pri_a28_evac_com_to_helicopter"]		= {-1, 5000, "ui_inGame2_Soldier_2", "army", "pri_a28_evac_com_name"},	-- actor override
--pri_a28_evac_com_ready
--pri_a28_evac_com_scene_end_when_strelok_dead
["pri_a28_actor_to_strelok"]			= {-4, 5000, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_a28_actor_scene_end_when_strelok_dead"]	= {-4, 5000, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker
["pri_a28_actor_scene_end"]			= {-4, 5000, "ui_inGame2_Hero", "", "st_actor_name"},	-- actor_visual_stalker

--- Garik's welcome to freeplay
["pri_a28_continuation"]	= {-1, 9000, "ui_inGame2_Garik", "stalker", "st_jup_b43_stalker_assistant"},	-- actor override
}

local snd_groups = {
["cc_fight"]	= {6, 1250, nil, nil, nil, 50},
["cc_wounded"]	= {9, 2500, nil, nil, nil, 35},
}

local last_caption_category = ""
local longest_caption_ends = 0
local delayed_cc = {}

function sound(sound, showtime, sender, sender_faction, sender_id, delay_sound)

	if db.cc_npc == nil then
		read_cc_ini()
	end
	if db.cc_npc == true then
		local current_time = time_global()
		local split_sound_string = {}
		local i = 1
		for w in string.gmatch(sound, "[%w_]+") do
			split_sound_string[i] = w
			i = i + 1
		end
		local cc_id, cc_category

		if split_sound_string[1] == "characters_voice" then
			if split_sound_string[2] == "scenario" then
				if not db.cc_vrb then
					if string.match(split_sound_string[4], "_greeting_%d") or string.match(split_sound_string[4], "_farewell_") then
						return true
					end
				end
				cc_category = "cc_scenario"
				cc_id = split_sound_string[4]

			elseif string.match(split_sound_string[2], "human_0") then
				if split_sound_string[4] == "states" then
					if split_sound_string[5] == "meet" then
						if (current_time > longest_caption_ends) or (last_caption_category ~= "cc_scenario") then
							if string.match(split_sound_string[6], "meet_use") then
								if #delayed_cc >= 1 then
									if delay_sound < 0 then delay_sound = -delay_sound - 501 end
								else
									local gt = time_global() + 500
									table.insert(delayed_cc, {sound, showtime, sender, sender_faction, sender_id, -delay_sound - 1, dt = gt})
									xr_s.register_callback("update", on_actor_update_cc, self)
									return true
								end
							else
								if not db.cc_vrb then
									return true
								end
							end
							if db.actor:is_talking() then
								return true
							end
							cc_category = "cc_generic"
							cc_id = cc_category .. "-" .. split_sound_string[3] .. "-" .. split_sound_string[6]
						else
							return true
						end
					else
						return false
					end

				elseif split_sound_string[4] == "reactions" then
					if split_sound_string[5] == "story" then
						if db.cc_icc then
							cc_category = "cc_effect"
							cc_id = cc_category .. "-" .. split_sound_string[6]
							cc_id = string.gsub(cc_id, "_%d+$", "_")
						else
							return true
						end
					else
						return false
					end

				elseif split_sound_string[4] == "help" then
					if split_sound_string[5] == "wounded_heavy" then
						if db.cc_icc then
							cc_category = "cc_wounded"
							cc_id = cc_category .. "-" .. split_sound_string[3] .. "-" .. "help"
						else
							return true
						end
					else
						return false
					end

				elseif split_sound_string[4] == "fight" then
					if split_sound_string[5] == "attack" then
						if db.cc_icc then
							cc_category = "cc_fight"
							cc_id = cc_category .. "-" .. split_sound_string[3] .. "-" .. "attack"
						else
							return true
						end
					else
						return false
					end

				else
					-- add any special "human_0x" cases here
					if string.match(split_sound_string[#split_sound_string], "pas_b400_") then
						cc_category = "cc_scenario"
						cc_id = split_sound_string[#split_sound_string]
					else
						return false
					end
				end
			else
				return false
			end

		elseif split_sound_string[1] == "device" or split_sound_string[1] == "ambient" then
			if db.cc_icc then
				cc_category = "cc_effect"
				cc_id = cc_category
				for i = 1, #split_sound_string do
					cc_id = cc_id .. "-" .. split_sound_string[i]
				end
			else
				return true
			end

		elseif split_sound_string[1] == "music" then
			if db.cc_icc then
				cc_category = "cc_effect"
				cc_id = cc_category
				for i = 1, #split_sound_string do
					cc_id = cc_id .. "-" .. split_sound_string[i]
				end
				cc_id = string.gsub(cc_id, "_%d+$", "_")
			else
				return true
			end

		else
			-- add any special full soundpath match cases here
			if sound == "anomaly\\steam_blowout" then
				if db.cc_icc then
					cc_category = "cc_effect"
					cc_id = cc_category .. "-anomaly-steam_blowout"
				else
					return true
				end

			elseif sound == "weapons\\n_desert_eagle_shot" then
				if db.cc_icc then
					cc_category = "cc_effect"
					cc_id = cc_category .. "-weapons-n_desert_eagle_shot"
				else
					return true
				end
			
			else
				return false
			end
		end

		local cc_text = game.translate_string(cc_id)
		if cc_text ~= cc_id then
			local distance_limit = 10001
			local cc_type
			if sender_faction == "object" then
				cc_type = 9
			else
				cc_type = -1
			end
			if not showtime then
				showtime = 5000
			elseif showtime < 2000 then
				showtime = 2000
			end
			if not delay_sound then delay_sound = 0 end
			local override
			if snd_ids[cc_id] then
				override = snd_ids[cc_id]
			elseif snd_groups[cc_category] then
				override = snd_groups[cc_category]
			end
			if override then
				if override[1] then cc_type = override[1] end
				if override[2] then showtime = override[2] end
				if override[3] then sender = override[3] end
				if override[4] then sender_faction = override[4] end
				if override[5] then sender_id = override[5] end
				if override[6] then distance_limit = override[6] end
			end
			if cc_type == "t" then
				cc_display_tutorial(cc_id)
				return true
			elseif cc_type > 0 then
				if distance_between_safe(sender, db.actor) < distance_limit then
					cc_display_normal(cc_id, showtime, cc_type)
				end
				return true
			else
				if type(sender) == "userdata" then
					local distance = distance_between_safe(sender, db.actor)
					if distance < distance_limit then
						if cc_type == -1 and distance < 12 then
							cc_type = -4
						end
					else
						return true
					end
				end
				cc_display_radio(sender, sender_faction, sender_id, showtime, cc_text, delay_sound, cc_type)
				last_caption_category = cc_category
				if current_time + showtime + delay_sound + 1000 > longest_caption_ends then
					longest_caption_ends = current_time + showtime + delay_sound + 1000
				end
				return true
			end
		end
	end
end

local colors = {
[1] = "closecaption_1",
[2] = "closecaption_2",
[3] = "closecaption_3",
[4] = "closecaption_4",
[5] = "cs_subtitles_npc",
[6] = "closecaption_6",
[7] = "cs_subtitles_actor",
[8] = "cs_subtitles_object",
[9] = "closecaption_9",
[10] = "cs_subtitles",
}

local cc_on = {0, 0, 0, 0}

function cc_display_normal(cc_id, showtime, color)
	local time_now = time_global()
	local time_ccend = (time_now + showtime + 300) / 1000
	if color == 0 then
		for i,v in ipairs(cc_on) do
			if v <= time_now then
				color = i
				break
			end
		end
		if color == 0 then color = 1 end
	end
	local tmpl = colors[color]
	local tmpls = tmpl .. "_shadow"
	local hud = get_hud()
	hud:AddCustomStatic(tmpls, true)
	local custom_static_shadow = hud:GetCustomStatic(tmpls)
	hud:AddCustomStatic(tmpl, true)
	local custom_static = hud:GetCustomStatic(tmpl)
	if custom_static_shadow ~= nil then
		custom_static_shadow:wnd():TextControl():SetTextST(cc_id)
		custom_static_shadow.m_endTime = time_ccend
	end
	if custom_static ~= nil then
		custom_static:wnd():TextControl():SetTextST(cc_id)
		custom_static.m_endTime = time_ccend
	end
	if color <= #cc_on then cc_on[color] = time_ccend * 1000 end
end

local msgtypes = {"st_tip", "st_memo", "st_sending_msg", ""}

function cc_display_radio(sender, sender_faction, sender_id, showtime, cc_text, delay_sound, cc_type)
	local msg_type = msgtypes[-cc_type]
	local texture, faction, name
	if type(sender) == "userdata" then
		texture = sender:character_icon()
		if sender:profile_name() ~= "actor" then
			faction = game.translate_string(sender:character_community())
		end
		name = sender:character_name()
	else
		if type(sender) == "table" then sender = sender[math.random(1, #sender)] end
		texture = string.sub(sender, 1)
	end
	if sender_faction then
		faction = game.translate_string(sender_faction)
	end
	if sender_id then
		if sender_id == "!" then
			name = sender_unidentified()
		else
			name = game.translate_string(sender_id)
		end
	end

	local news_caption = ""
	if msg_type and msg_type ~= "" then
		news_caption = game.translate_string(msg_type)
	end
	if faction and faction ~= "" then
		if news_caption ~= "" then
			news_caption = news_caption .. " - " .. faction
		else
			news_caption = faction
		end
	end
	if name and name ~= "" then
		if news_caption ~= "" then
			news_caption = news_caption .. " - " .. name
		else
			news_caption = name
		end
	end
	if news_caption ~= "" then
		news_caption = news_caption..":"
	end
	local clr = "%c[ui_2]"
	db.actor:give_game_news(news_caption, clr .. cc_text, texture, delay_sound+500, showtime, 1)
	return true
end

function cc_display_tutorial(cc_id)
	local running = game.has_active_tutorial()
	if running == false then game.start_tutorial(cc_id) end
end

function read_cc_ini()
	-------- Read values for closecaptions
	local cc = "closecaption"
	local cc_npc, cc_vrb, cc_icc = false, false, false
	cc_npc = load_variable("cc_npc", 0)
	if cc_npc == 0 then
		local ini = ini_file("misc\\closecaption.ltx")
		if ini:section_exist(cc) then
			if ini:line_exist(cc, "cc_ingame_npc") then
				cc_npc = ini:r_bool(cc, "cc_ingame_npc")
			end
			if ini:line_exist(cc, "cc_ingame_vrb") then
				cc_vrb = ini:r_bool(cc, "cc_ingame_vrb")
			end
			if ini:line_exist(cc, "cc_ingame_cc") then
				cc_icc = ini:r_bool(cc, "cc_ingame_cc")
			end
		end
		db.cc_npc = cc_npc
		db.cc_vrb = cc_vrb
		db.cc_icc = cc_icc
		save_variable("cc_icc", cc_icc)
		save_variable("cc_vrb", cc_icc)
		save_variable("cc_npc", cc_npc)
	else
		cc_vrb = load_variable("cc_vrb", cc_vrb)
		cc_icc = load_variable("cc_icc", cc_icc)
		db.cc_npc = cc_npc
		db.cc_vrb = cc_vrb
		db.cc_icc = cc_icc
	end
end

function on_actor_update_cc()
	if #delayed_cc >= 1 then
		if time_global() >= delayed_cc[1].dt then
			local d = delayed_cc[1]
			closecaption.sound(d[1], d[2], d[3], d[4], d[5], d[6])
			table.remove(delayed_cc, 1)
		end
	else
		xr_s.unregister_callback("update", on_actor_update_cc)
	end
end

-- Preconditions for SSU communication scene of STALKER: Call Of Pripyat
function both_heli_info()
	return has_alife_info("zat_b101_both_heli_info") and db.cc_npc == true
end
function not_both_heli_info()
	return (not has_alife_info("zat_b101_both_heli_info")) and db.cc_npc == true
end
function cc_npc_disabled()
	return db.cc_npc ~= true
end

function is_cc_npc_enabled()
	if db.cc_npc == nil then read_cc_ini() end
	if db.cc_npc == true then return true else return false end
end

function get_game_version()	-- detect real game version
	local ver = 1600
	if dialogs_jupiter.zat_b106_trapper_reward ~= nil then		-- v1.6.01 addition
		local GSver		= _G.main_menu.get_main_menu():GetGSVer()
		ver			= tonumber((string.gsub(GSver, "%p", "")))
		if (ver == nil) or (ver < 1600) then ver = 1601 end
	end
	return ver
end

function sender_unidentified()
	local senders = {
		"",			-- a couple of random chars from charset below
		"st_msgfrom_err1",	-- "[sender unknown]"
		"st_msgfrom_err2",	-- "<!DATA_ERROR!>"
		"st_msgfrom_err3",	-- "=?Network failure"
		"st_msgfrom_err1",	-- "[sender unknown]"
		"",			-- a couple of random chars from charset below
	}
	msg = senders[math.random(1, #senders)]
	if msg ~= "" then
		return game.translate_string(msg)
	else
		local length = 7 + math.random(1, 7)
		local charset = "@AÁBCDEÉFGHIÍJKLMNOÓÖÕPQRSTUÚÜÛVWXYZ" ..
				"`aábcdeéfghiíjklmnoóöõpqrstuúüûvwxyz" ..
				[[!"#&'()*+,-./0123456789:;<=>?^_{|}]] ..
				"~€‚„…‰ŒŽ‘’“”•–—™žŸ¡¢£¥§¨©ª«­®¯°±²³´µ" ..
				"¶·¸¹º»¼½¾¿ÀÂÃÄÅÆÇÈÊËÌÎÏÐÑÒÔ×ØÙÝÞßàâã" ..
				"äåæçèêëìîïðñòô÷øùýþÿ"
		local result = {}
		for i = 1, length do
			local r = math.random(1, charset:len())
			result[i] = string.sub(charset, r, r)
		end
		return table.concat(result)
	end
end

-- Code portions from the excellent AMK mod --
function save_variable(variable_name, value)
  xr_logic.pstor_store(db.actor, variable_name, value)
end

function load_variable(variable_name, value_if_not_found)
  return xr_logic.pstor_retrieve(db.actor, variable_name, value_if_not_found)
end

function del_variable(variable_name)
  if db.storage[db.actor:id()].pstor[variable_name] then
    db.storage[db.actor:id()].pstor[variable_name] = nil
  end
end
----------------------------------------------

